export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTERED_REQUEST = "USER_REGISTERED_REQUEST"
export const USER_REGISTERED_SUCCESS = "USER_REGISTERED_SUCCESS"
export const USER_REGISTERED_FAIL = "USER_REGISTERED_FAIL"
